name(shakil,gpa(3.65,university(comilla_university))).
name(mahfuz,gpa(3.49,university(comilla_university))).
name(shanto,gpa(3.49,university(comilla_university))).
name(mandol,gpa(3.49,university(comilla_university))).
name(sifat,gpa(3.51,university(comilla_university))).
name(moin,gpa(3.49,university(comilla_university))).
name(samrat,gpa(3.70,university(comilla_university))).
name(majhar,gpa(3.63,university(comilla_university))).
name(zilani,gpa(3.69,university(comilla_university))).
name(mamun,gpa(3.23,university(comilla_university))).
